#!/bin/bash

usage(){
    printf 'Usage: %s [-e] [-t] <num_peers>\n' "$0"
    printf "\t%s\n" "<num_peers>: number of instances of the app to run"
    printf "\t%s\n" "-e: boolean flag for encrypting communication (default off)"
    printf "\t%s\n" "-t: boolean flag to run over tor (default off)"

}
OPTIND=1
encrypt=0
tor=0
while getopts eth opt; do
    case $opt in 
        e | -encrypt )
            encrypt=1
            ;;
        t | -tor )
            tor=1
            ;;
        h | -help )
            usage
            exit
            ;;
        *)
            usage
            exit 1
            ;;
    esac    
done

shift $((OPTIND-1))

numPeers=$@
if [ -z "$numPeers" ]
then
   numPeers=1
fi

if [ $tor == 1 ]
then
    echo "running tor with $numPeers $encrypt"
    . ./dockertorgo $numPeers $encrypt
else
    echo "running non-tor with $numPeers $encrypt"
    . ./dockergo $numPeers $encrypt
fi